//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblvariationimages
    {
        public int Variationimageid { get; set; }
        public string ImagePath { get; set; }
        public int VariationID { get; set; }
        public int ProductID { get; set; }
    }
}
